# Stage 1: Build React Vite app
FROM node:23-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Define environment variables
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

# Build the React app
COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:1.27.3-alpine-slim

WORKDIR /etc/nginx

RUN apk add --no-cache openssl

RUN mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/server.key -out /etc/nginx/certs/server.crt \
    -subj "/CN=localhost"

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
