version: "3.9"

services:
  server:
    build:
      context: server
      dockerfile: dockerfile.dev.server
    container_name: fshare_server
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - data_volume:/app/data
    env_file:
      - .env.server
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  client:
    build:
      context: client
      dockerfile: dockerfile.dev.client
    container_name: fshare_client
    env_file:
      - .env.client
    volumes:
      - ./certs/server.crt:/etc/nginx/certs/server.crt
      - ./certs/server.key:/etc/nginx/certs/server.key
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--no-check-certificate", "https://127.0.0.1/json/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

volumes:
  static_volume:
    name: fshare_static_volume
  media_volume:
    name: fshare_media_volume
  data_volume:
    name: fshare_data_volume
