version: "3.9"

services:
  server:
    image: adhupraba/fshare-server:latest
    container_name: fshare_server
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - data_volume:/app/data
    env_file:
      - .env.server
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    network_mode: "host"

  client:
    image: adhupraba/fshare-client:latest
    container_name: fshare_client
    env_file:
      - .env.client
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:2500/json/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    network_mode: "host"

volumes:
  static_volume:
    name: fshare_static_volume
  media_volume:
    name: fshare_media_volume
  data_volume:
    name: fshare_data_volume
