name: Deploy FShare Server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - server/**
      - .github/workflows/server.yaml
      - docker-compose.prod.yaml

jobs:
  server-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "${{ secrets.DOCKERHUB_USERNAME }}/fshare-server"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./server/dockerfile.prod.server
          context: server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Prepare .env
        run: |
          touch .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "SERVER_FILE_ENCRYPTION_KEY=${{ secrets.SERVER_FILE_ENCRYPTION_KEY }}" >> .env
          echo "MFA_JWT_SECRET_KEY=${{ secrets.MFA_JWT_SECRET_KEY }}" >> .env
          echo "AUTH_JWT_SECRET_KEY=${{ secrets.AUTH_JWT_SECRET_KEY }}" >> .env
          echo "DEBUG_MODE=${{ secrets.DEBUG_MODE }}" >> .env
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
          echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> .env

      - name: Sync code to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
          source: ./docker-compose.prod.yaml,./.env
          target: /home/${{ secrets.SERVER_USER }}/fshare/

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_KEY_PASSPHRASE }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/fshare
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker compose -f docker-compose.prod.yaml stop server
            docker compose -f docker-compose.prod.yaml rm -f server
            docker compose -f docker-compose.prod.yaml up -d server

      - name: Cleanup
        run: |
          rm .env
